# Generated by Django 3.0.5 on 2020-05-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mililitros', models.IntegerField()),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('artesanal', models.BooleanField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
